### ISSUE TITLE
Cleanup auxiliary interval constructors

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/TaylorModels.jl#104]
https://github.com/JuliaIntervals/TaylorModels.jl/pull/103 introduces some auxiliary interval constructors. This is a reminder to use `IntervalArithmetic.zero` and `IntervalArithmetic.symmetric_box` once https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/446 is ready.

**Comment by lbenet** [comment]
Fixed by #126
