### ISSUE TITLE
Update to TaylorSeries v0.12

### ISSUE THREAD

**Issue by schillic** [JuliaIntervals/TaylorModels.jl#134]
You probably also want to enable CompatHelper again ([here](https://github.com/JuliaIntervals/TaylorModels.jl/actions/workflows/CompactHelper.yml)).
 Sorry @lbenet for the déjà-vu :sweat_smile:

**Comment by lbenet** [comment]
Essentially done (https://github.com/JuliaIntervals/TaylorModels.jl/commit/cd837f3f100194bfa25e94ffd4d97dc26669b0bc) 😄 ... it's a question of time now.
