### ISSUE TITLE
Update to TaylorIntegration v0.10

### ISSUE THREAD

**Issue by schillic** [JuliaIntervals/TaylorModels.jl#138]
CompatHelper fell asleep again...

**Comment by lucaferranti** [comment]
I think compathelper goes to sleep after 30 days of inactivity :/ is it possible to disable that?

**Comment by schillic** [comment]
I have not used it, but see [here](https://stackoverflow.com/questions/67184368/prevent-scheduled-github-actions-from-becoming-disabled).
