### ISSUE TITLE
Reactivate CompatHelper

### ISSUE THREAD

**Issue by schillic** [JuliaIntervals/TaylorModels.jl#141]

**Comment by lucaferranti** [comment]
done

**Comment by lbenet** [comment]
Sorry for the question, but what is "reactive compat helper?

**Comment by schillic** [comment]
`TaylorSeries` got a new release, but it is not propagated here because `CompatHelper` is inactive. GitHub deactivates bots after 60 days of inactivity. So I suggested to re-activate it :slightly_smiling_face: I expect it will send a PR in a few hours.

**Comment by lbenet** [comment]
Thanks for the stupid question... "too early to roch-and-roll..." 😄

**Comment by schillic** [comment]
The PRs arrived, but they did not automatically trigger a build. I think you need to add an SSH key for that.

https://github.com/JuliaIntervals/TaylorModels.jl/blob/66b0e9c8503c44010e47dc418ded9c8cbde59c83/.github/workflows/CompactHelper.yml#L14

**Comment by lucaferranti** [comment]
> The PRs arrived, but they did not automatically trigger a build. I think you need to add an SSH key for that.

Last time I tried this in ICP it broke the whole workflow :/ :P
