### ISSUE TITLE
Add simplify function

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/TaylorModels.jl#24]
Add a `simplify` function given a cutoff threshold such that the terms with small enough coefficients, given the threshold, are absorbed to its interval enclosure onto the remainder part.

**Comment by mforets** [comment]
Oh indeed, i was assuming that `pol :: Taylor1{T}` can be sparsely represented, so `simplify` would just delete some coefficients. I think that this can coexist with an option to reduce the order, so long as the new TM is an over-approximation.

**Comment by dpsanders** [comment]
TaylorSeries.jl uses a dense representation, even for higher dimensions.

**Comment by mforets** [comment]
Ok, i see. Perhaps still useful to add a method `reduce` (?) to return an overapproximating TM of lower order.

**Comment by mforets** [comment]
I think that this idea is not applicable for the reason stated above (TaylorSeries uses a dense representation, even for higher dimensions, so it makes all products even when some coeffs are zero).
