### ISSUE TITLE
Documentation link broken in readme.md

### ISSUE THREAD

**Issue by ShreyanshTripathi** [JuliaIntervals/TaylorModels.jl#33]

**Comment by lbenet** [comment]
Sorry for that. For the time being, I suggest to look at the tests. If you have any problems or questions, we may answer them here.

**Comment by lbenet** [comment]
#36 may have solved this; the docs take some time to be deployed so, if there is a problem, please report it here. Do not expect too much of the documentation yet... (lack of time).

**Comment by lbenet** [comment]
Reopening; see https://travis-ci.org/JuliaIntervals/TaylorModels.jl/jobs/515849944

**Comment by lbenet** [comment]
@dpsanders I think you have to deploy the keys to allow push access for the docs to be deployed. see [this](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#SSH-Deploy-Keys-1). I think I do not have the permissions to do that.

**Comment by dpsanders** [comment]
Is there some kind of permission I need to give you for you to be able to do this?

**Comment by dpsanders** [comment]
I made you admin of the repo; I guess this allows you to do things like this.

**Comment by lbenet** [comment]
I will give it a try, though I am not sure it will work (since the repo is under JuliaIntervals "username").

**Comment by lbenet** [comment]
Sorry for the noise; it did work (with some small corrections).

**Comment by lbenet** [comment]
It finally worked! Re-closing.
