### ISSUE TITLE
Add benchmark suite

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/TaylorModels.jl#35]
See eg. Tables 3-6 in [AGK18](https://easychair.org/publications/paper/9Tz3).

**Comment by mforets** [comment]
We've worked out the reference values for those benchmarks using SDP, since i didn't find them in that paper, see [TaylorModels_Benchmark_RefValues](https://github.com/mforets/escritoire/blob/master/sets/TaylorModels_Benchmark_RefValues.ipynb). In a PR to come we've evaluated the range of each polynomial with and without normalization, to measure accuracy and speed. This sets up the ground to compare with other approaches, such as brand and bound, interval arithmetic, etc.

CC: @Aadesha

**Comment by dpsanders** [comment]
Great! I suggest adding timings in the notebook, and saving the results to a DataFrame or similar.

**Comment by lbenet** [comment]
Excellent! Looking forward to the PR

**Comment by mforets** [comment]
Done in https://github.com/JuliaIntervals/TaylorModels.jl/pull/50.
