### ISSUE TITLE
links to docs [stable] gives a 404

### ISSUE THREAD

**Issue by tlienart** [JuliaIntervals/TaylorModels.jl#40]
https://juliaintervals.github.io/TaylorModels.jl/stable --> 404

https://juliaintervals.github.io/TaylorModels.jl/latest/ --> works fine

**Comment by lbenet** [comment]
Thanks for reporting. 

I guess this is due to the fact that we didn't tag a new version when the docs were merged to master. I leave this open as a reminder that we should tag soon a new version. In any case, the documentation needs also to be enlarged.

**Comment by lbenet** [comment]
We just tagged v0.1.1, so the stable docs should work fine. I'm therefore closing this.
