### ISSUE TITLE
Tag v0.1.1

### ISSUE THREAD

**Issue by lbenet** [JuliaIntervals/TaylorModels.jl#49]

**Comment by lbenet** [comment]
@JuliaRegistrator register

**Comment by dpsanders** [comment]
Since support is being dropped for a version of Julia, this should be a minor version I believe?

**Comment by lbenet** [comment]
Good point. As mentioned in #48, we will do that once we rely on `TaylorIntegration.jl` v0.5.0 and above. I think it is ok to wait a bit :-)

**Comment by lbenet** [comment]
TaylorModels v0.1.1 is tagged. Closing.

cc @mforets
