### ISSUE TITLE
Bump TaylorModels

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/TaylorModels.jl#58]
Commit https://github.com/JuliaIntervals/TaylorModels.jl/commit/f51a27de3b3288543cc55534474d168683efa9f4 is not included yet in the latest tagged version but it is needed in Reachability.jl.

**Comment by lbenet** [comment]
I just merged #58; tagging...

**Comment by lbenet** [comment]
@JuliaRegistrator register

**Comment by lbenet** [comment]
Version 0.3.0 is tagged and registered! Thanks @mforets for the remainder!

Closing.
