### ISSUE TITLE
Generalize validated ODEs to receive an initial Taylor model

### ISSUE THREAD

**Issue by mforets** [JuliaIntervals/TaylorModels.jl#92]
The method https://github.com/JuliaIntervals/TaylorModels.jl/blob/4dd5d17555b375386d58282b64507e1437869fd7/src/validatedODEs.jl#L401

currently receives `(qq0, δq0)` representing a box. It would be nice if it can handle an initial Taylor model reach-set (TaylorModel1 of TaylorN's); the conversion from a box to a TM can be done as a pre-processing step.

**Comment by lbenet** [comment]
Thanks for reporting and sorry for the delay to get into this...

Can you include an example of  the way you would like to call that function, I mean, of the `TaylorModel1` vector you want to pass?

**Comment by mforets** [comment]
(we continued this conversation on another meeting last year) the taylor model i want to pass is of the same type as that returned by the validated_integ function (before approximating with a box). in other words, a [TaylorModelReachSet](https://juliareach.github.io/ReachabilityAnalysis.jl/dev/lib/reachsets/#ReachabilityAnalysis.TaylorModelReachSet). this will be used to chain results of flowpipe computations. it is also useful if you want to propagate an initial taylor model from the start.

i began to make the required updates in validated_integ in https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/342, but it is not finished yet. i had some doubts abut how to adapt lines 433-447 here https://github.com/JuliaIntervals/TaylorModels.jl/blob/7e8b31eb07bbb84c8d7d55c57c4c49621f3ddc14/src/validatedODEs.jl#L433
